
export const GET_REPOSITORIES = 'GET_REPOSITORIES';
export const GET_PULL_REQUESTS = 'GET_PULL_REQUESTS';
export const GET_COMMITS = 'GET_COMMITS';
export const REPOSITORIES_ERROR= 'REPOSITORIES_ERROR';
export const PULL_REQUESTS_ERROR= 'PULL_REQUESTS_ERROR';
export const COMMITS_ERROR='COMMITS_ERROR';
export const USER_NAME="hemant-chitte";

